### ISSUE TITLE
logarithmic scale support

### ISSUE THREAD

**Issue by snorkysnark** [ckjellson/textalloc#10]
Distance computation in incorrect when using axis scale other than "linear"
Example:
![2024-01-24_21-30](https://github.com/ckjellson/textalloc/assets/36006338/fab311b9-4e7f-4779-8b46-34ffbc5c3126)

**Comment by ckjellson** [comment]
Good point! I am actually not sure what is the best way to solve this, and I think other things break down as well, such as overlap with lines. Will have to think about how to do this, if you have any suggestion feel free to

**Comment by Phlya** [comment]
You can check out the code in adjustText... It has been a pain for years figuring out all the different types of axes, transforms, units in matplotlib to make it work with any plots. AFAIK now it works with anything, except not sure about all the different backends, someone complained about some of them at some point... The idea is to transform all coordinates to display coordinates, perform all calculations, and then transform back

Up until and including this function, is what you need, plus all the stuff with transforms in the main function: https://github.com/Phlya/adjustText/blob/12d94cbdd38bc0981cfd0fd9470085c763a166bc/adjustText/__init__.py#L125

**Comment by ckjellson** [comment]
Thank you for the tip! I will look into it as soon as I have time to check it out.

**Comment by ckjellson** [comment]
Added support of log-scaling any or both axis. Currently requires providing the chosen logscale base for each non-linear axis.
Example:

```
x = [1,2,3,4,5,10,15,16,2000]
y = [1,2,3,4,5,10,15,160000,2000]
labels = [f"long_word_{i}" for i in range(len(x))]
fig,ax = plt.subplots(figsize=(10,10))
ax.scatter(x,y)
base = 10
ax.set_yscale("log", base=base)
ax.set_xscale("log", base=base)
ta.allocate_text(fig,ax,x,y,labels,x_scatter=x, y_scatter=y, seed=42, linewidth=0.5, x_logscale_base=base, y_logscale_base=base)
```
![02795755-b2c4-4b5c-b2a7-001286c8d12a](https://github.com/ckjellson/textalloc/assets/37980849/376e0f06-6e31-4696-9c72-ebeda80807ba)

**Comment by ckjellson** [comment]
Moved to using display coordinates, so x_logscale_base/y_logscale_base is no longer needed.
