### ISSUE TITLE
Avoid drawing new lines through text boxes

### ISSUE THREAD

**Issue by mrmbernardi** [ckjellson/textalloc#11]
When the `draw_lines` parameter is `True`, lines are draw from the text boxes to their respective points. However, these new lines can still overlap with text boxes. 

![image](https://github.com/ckjellson/textalloc/assets/7877312/f9b8f6c7-4223-4d8b-a429-887481b06fb9)

I'm thinking line drawing can be moved into the main loop and the lines can be added to `lines_xyxy` as it goes, perhaps with a setting to toggle this new behaviour.

**Comment by ckjellson** [comment]
Thanks for the request, added option "avoid_label_lines_overlap" that should do the trick!

It was actually a bit trickier than one would think 😅 It is not enough to check that the new box is not overlapping any previously added lines, but I also had to check that the potential new line that will be drawn to the new box do not overlap any previously drawn boxes!

**Comment by mrmbernardi** [comment]
I tested it with the setting and it works. Thank you for the quick turnaround!
