### ISSUE TITLE
Support older python 3 versions

### ISSUE THREAD

**Issue by ews-ffarella** [ckjellson/textalloc#15]
Hi! Great lib. 

Unfortunately my company is stuck with python 3.6. 😭 

Could we maybe make tqdm as an optional dependencies and show the progress bar only if the import is successful?

This might increase the adoption of this package as well.

**Comment by ckjellson** [comment]
Hi, thanks!

Added support for python 3.6 using your suggestion. I have tried to verify that it works properly (my first and only time so far creating a pypi-package), please reopen if there are any issues.

**Comment by ews-ffarella** [comment]
Thanks a lot!
