### ISSUE TITLE
Lines not connecting with text from east direction

### ISSUE THREAD

**Issue by OscarPellicer** [ckjellson/textalloc#17]
Hi! Nice library. I have struggled with the problem of overlapping for a long time, and your library seems to do a pretty good job with it.
I am having this problem where the lines are not connected to the text from the east direction. The error seems to be proportional to text length, as it smaller for shorter text.

![image](https://github.com/ckjellson/textalloc/assets/18261666/5564173f-144b-4232-b0e1-7456f237bed5)

Also, unrelated to the above, how do I change the alignment of the text (which is important if the text has newlines, for instance). I try to pass `va='center', ha='center'` but matplotlib throws an ArgumentError.

Please let me know if you need more info! It is quite hard for me to provide a reproducible example with the data I'm using.

Regards,
Oscar.

**Comment by OscarPellicer** [comment]
This is the command I'm using by the way. Note that I don't see the src_crs argument do anything visible:
```
ta.allocate_text(fig, ax, text_x, text_y, text_content, #[t.replace('\n', ' ') for t in text_content], 
                     x_scatter=text_x, y_scatter=text_y, textsize=14, zorder=11, linecolor=text_color,
                     src_crs=ccrs.TransverseMercator(), avoid_label_lines_overlap=True, max_distance=0.1)
```

**Comment by OscarPellicer** [comment]
Hi, thanks for the quick answer!

Regarding the `kwargs`, I think there are three options:
 - Define arguments `text_kwargs` and `plot_kwargs` as explicit dictionaries of kwargs to pass to each of the functions, similar to what seaborn does: [an example](https://seaborn.pydata.org/generated/seaborn.boxenplot.html#:~:text=box_kws%3DNone%2C%20flier_kws%3DNone%2C%20line_kws%3DNone)
 - Check the user `kwargs` against all the possible `kwargs` in both `text` and `plot`, and pass the user `kwargs` to each function depending on what `kwargs` they support. However, I don't think there is an automatic way of getting the `kwargs` of a function, which is a big problem. Also, this is a bit obfuscated and [explicit is better than implicit](https://peps.python.org/pep-0020/#:~:text=Explicit%20is%20better%20than%20implicit.)
 - Something in the middle: have `**kwargs`  for `text` (since this is the most common use case) and have an explicit  `plot_kwargs`  dict for `plot`.  This is actually exactly what seaborn does, if you look again at the example.

I like the third option the most.

**Comment by ckjellson** [comment]
I believe this issue is finally solved, even though the aspect had been set with the image, the fig does not update automatically, meaning that it had to be redrawn without rendering to update. Now hopefully everything should work properly!

Your above suggestion has also been implemented.
