### ISSUE TITLE
Poor Result when avoiding a polygonal curve

### ISSUE THREAD

**Issue by ThomasParistech** [ckjellson/textalloc#18]
Thanks for your great tool

I'm drawing text labels next to specific points along a curve.

I'd like to avoid collisions between text-boxes but also with the curve itself. Unfortunately passing the curve points in x and y results in a clearly non-optimal solution. The bottom label crosses the line and other labels seem to be quite far from their expected target position.

I've also tried "adjustText" (https://github.com/Phlya/adjustText/issues/173). Your solution seems to work better, but still not perfectly suited.

Question: Am I using textalloc in a incorrect way? Or should I implement a custom solution?

```
ta.allocate_text(plt.gcf(), plt.gca(),
                 list_x, list_y,
                 list_text,
                 x_scatter=x_peaks, y_scatter=y_peaks,
                 textsize=8,
                 textcolor="b",
                 x_lines=[curve_x], y_lines=[curve_y],
                 max_distance=0.1,
                 min_distance=0.012,
                 margin=0.01,
                 linewidth=0.5,
                 nbr_candidates=1000,
                 draw_lines=True)
```

![image](https://github.com/ckjellson/textalloc/assets/35526351/a0979179-8bd7-4d94-809d-2b46cc9d846d)

**Comment by ckjellson** [comment]
Hi, your usage looks correct to me, and it should definitively work for your scenario. Without all your code it is a bit difficult to find the reason for why it looks completely wrong, but I suspect it could be related to setting aspect_ratio, transforms and/or plotting on an image, which I'm having issues with and will try to solve when I can find the time (https://github.com/ckjellson/textalloc/issues/13, https://github.com/ckjellson/textalloc/issues/17).

Have you set the aspect ratio yourself, used a transform in previous calls, or done anything with images in the plot?

Created an example which works for me at least:

```
import textalloc as ta
curvex = [1,2,3,4,5,4,3,4,5,6,7,8,9]
curvey = [0,3,6,4,7,8,9,9,6,4,3,2,5]

fig,ax = plt.subplots()
ax.plot(curvex, curvey)
ta.allocate_text(plt.gcf(), plt.gca(),
                 curvex, curvey,
                 ["testingtesting" for _ in curvex],
                 textsize=8,
                 textcolor="b",
                 x_lines=[curvex], y_lines=[curvey],
                 max_distance=0.15,
                 min_distance=0.012,
                 margin=0.01,
                 linewidth=0.5,
                 nbr_candidates=1000,
                 draw_lines=True)
```
![image](https://github.com/ckjellson/textalloc/assets/37980849/1cace4d1-0ca3-4cdc-830d-89a5837d49f5)

**Comment by ThomasParistech** [comment]
Your example looks great!
I'll generate a snippet to reproduce the error

**Comment by ThomasParistech** [comment]
Here's a minimal reproducible example (With the JSON data).

Indeed, I'm calling `plt.axis('equal')` and `plt.gca().invert_yaxis()` which seem to perturb your code.
It works perfectly fine without these calls.

For the Y-inversion I can easily transformed the Y values directly. 

```
import json
import matplotlib.pyplot as plt
import textalloc as ta

path = "data/test.json"

with open(path, encoding="utf-8") as f:
    data = json.load(f)
    curve_x = data["curve_x"]
    curve_y = data["curve_y"]
    list_x = data["list_x"]
    list_y = data["list_y"]
    list_text = data["list_text"]

plt.plot(curve_x, curve_y, color="r", lw=2)
plt.plot(list_x, list_y, '^', color="g", markersize=10)


ta.allocate_text(plt.gcf(), plt.gca(),
                 list_x, list_y,
                 list_text,
                 x_scatter=list_x, y_scatter=list_y,
                 textsize=8,
                 textcolor="b",
                 x_lines=[curve_x], y_lines=[curve_y],
                 max_distance=0.1,
                 min_distance=0.012,
                 margin=0.01,
                 linewidth=0.5,
                 nbr_candidates=1000,
                 draw_lines=True)

# plt.axis('equal')
# plt.gca().invert_yaxis()

plt.show()
```
![image](https://github.com/ckjellson/textalloc/assets/35526351/de7d60f5-1f53-4742-b171-d654afb04b09)

[test.json](https://github.com/ckjellson/textalloc/files/15142994/test.json)

**Comment by ckjellson** [comment]
Great, then there doesn't seem to be any new problems, so I will try to  find time to solve the aspect ratio issues. Hope you can make it work well enough in the mean time!

By the way, I noticed your code takes multiple seconds to finish and it's probably because there are so many line-segments in the polygon. You could probably decrease nbr_candidates (to 50-100) and instead play with max_distance, min_distance, and margin to get what you want much quicker.

**Comment by ThomasParistech** [comment]
Great

I used a really a high value for `nbr_candidates` just to make sure it wasn't the source of imprecision. I'll decrease it and play with max_distance, min_distance, and margin

Thanks :)

**Comment by ThomasParistech** [comment]
@ckjellson 
I've just tested decreasing the number of candidates to 100 and it crosses the polygon.
Since performance is not an issue, I'll stick to a large number!

nbr_candidates=100:
![image](https://github.com/ckjellson/textalloc/assets/35526351/5546860d-65b0-4076-8051-99c9160b04ed)

nbr_candidates=1000:
![image](https://github.com/ckjellson/textalloc/assets/35526351/cc1c6659-78a6-491b-8591-181b4f9db032)

**Comment by ckjellson** [comment]
Alright, I think it is an effect of setting a very low min_distance while the text-strings are long, making the nearest candidates untenable. In other words increasing the min_distance could help.

Additionally, I believe that the aspect ratio issues are finally solved as well!

**Comment by ThomasParistech** [comment]
Ok I see! :+1: 

Unfortunately, adding the  `ha='center'` to the kwargs isn't correctly handled (eventhough it doesn't change the actual bbox around the text). And `plt.axis('equal')` and `plt.gca().invert_yaxis()` are still not handled correctly as well :thinking: 

with  `ha='center'`:
![image](https://github.com/ckjellson/textalloc/assets/35526351/7b9e5a2f-0a3e-483f-9c4f-dd6ab5c417e1)

**Comment by ckjellson** [comment]
plt.axis('equal') or any other aspect, and also plotting on images now works, you just have to run it before allocate_text.

The aspect ratio fix did not solve the issues with invert_axis and ha="center" as you say, so I'll reopen this issue and see what can be done.

**Comment by ckjellson** [comment]
Moved to using display coordinates and added support for the ha-argument, so both plt.gca().invert_yaxis() and ha="center" should now work. Please let me know if you are still having issues!

**Comment by ThomasParistech** [comment]
Thanks!!
Unfortunately I'm currently on vacation and won't have access to my laptop until the end of the week. I'll test it on my data once I'm back :)

**Comment by ThomasParistech** [comment]
Thanks, `plt.axis('equal') ` and `ha=center` work great!

but the lines are not correctly drawn when `plt.gca().invert_yaxis()` is called. I'll flip my Y coordinates manually beforehand

![image](https://github.com/ckjellson/textalloc/assets/35526351/f5027817-096a-4187-9e62-47b2b7ead4e4)

**Comment by ckjellson** [comment]
Did you run plt.gca().invert_yaxis() before or after the call to textalloc? For me it works perfectly as long as all transformations of the plot have been performed before the call to textalloc.

**Comment by ThomasParistech** [comment]
You're right, sorry :+1:
