### ISSUE TITLE
Support for 3D scatter plots

### ISSUE THREAD

**Issue by sahilm89** [ckjellson/textalloc#23]
Hi,

Thanks for this, it has been very useful! I am wondering if it would be possible to support 3D scatter plots. I think it would be quite useful (I for sure would use it :) ).

Thanks again!
Sahil

**Comment by ckjellson** [comment]
Hi,

I think it should be possible (since I recently made changes to using display coordinates), will look into it soon! Thank you for the suggestion and great that you found it useful even in 2D :)

/Christoffer

**Comment by ckjellson** [comment]
Made an update so that 3D plotting is now supported. It was a bit more tricky than I expected, so if you try it out and find something that is not working properly, please open a new issue! :)
You can check out the example in the readme or the demo notebook for how to use the new functionality.
