### ISSUE TITLE
Support for multiple Axes with different scales?

### ISSUE THREAD

**Issue by Buuugle** [ckjellson/textalloc#25]
Hi,

First of all, thank you for creating this library! It really helps me with my project!
I'm using it to annotate a graph representing values that evolve over time.
On a figure, I plot several types of data that have different y-axes with different scales. All the data have the same x-axis (time) thanks to `twinx` function.
I want to add annotations that avoid all the points in the figure on all the axes with your `allocate` function, but the `x_scatter` and `y_scatter` parameters can only refer to a single `Axes` object given in the `ax` parameter.
I wonder if it would be possible to implement a way of giving several axes as parameters, with their corresponding points?

Thanks again!

**Comment by ckjellson** [comment]
Hi, great that you found it useful!

I guess it should be possible, but I'm not sure how and if it would make sense to implement it. Would using a workaround such as the one below work in your case? I.e. transforming the points so that all plotting is done in one of the axes, but you can still use the second axes for visualization:

```
import matplotlib.pyplot as plt
import numpy as np
import textalloc as ta

# Create some mock data
t = np.arange(0.01, 10.0, 0.1)
data1 = np.exp(t)
data2 = np.sin(2 * np.pi * t)

fig, ax1 = plt.subplots()

# Plot exp-data
color = 'tab:red'
ax1.set_xlabel('time (s)')
ax1.set_ylabel('exp', color=color)
ax1.scatter(t, data1, c=color)
ax1.tick_params(axis='y', labelcolor=color)

# Set up second ax and limits
ax1_ylim = ax1.get_ylim()
ax2_ylim = (np.min(data2), np.max(data2))
ax2 = ax1.twinx()
ax2.set_ylim(ax2_ylim)

# Transform and plot sin-data
data2_transformed = (data2 - ax2_ylim[0]) / (ax2_ylim[1] - ax2_ylim[0]) * (ax1_ylim[1] - ax1_ylim[0]) + ax1_ylim[0]
color = 'tab:blue'
ax1.scatter(t, data2_transformed, c=color)

# Add ax2 for visualization
ax2.set_ylabel('sin', color=color)
ax2.set_ylim(ax2_ylim)
ax2.tick_params(axis='y', labelcolor=color)

# Allocate text labels
x = np.hstack([t, t])
y = np.hstack([data1, data2_transformed])
ta.allocate(ax1, x, y, ["Something" for _ in range(len(x))], x_scatter=x, y_scatter=y, draw_all=False)

fig.tight_layout()
plt.show()
```
![image](https://github.com/user-attachments/assets/2c8aeed3-57e3-43df-a86d-7e0fb081ab4e)

**Comment by Buuugle** [comment]
Thanks! This method works well, but I now have a problem similar to #17: because there's an axis on the right, the plot is compressed and the text line doesn't connect on the east side. Here are some screenshots to illustrate the problem:
- With right axis:
![test1](https://github.com/user-attachments/assets/54fd4654-de03-4c36-8cee-6e1fea8b800f)
- Without:
![test](https://github.com/user-attachments/assets/3f3306b3-f9d9-4721-87e7-3788e757db83)
