### ISSUE TITLE
Thanks 🚴‍♂️🏞️

### ISSUE THREAD

**Issue by ThomasParistech** [ckjellson/textalloc#28]
Thank you for the effort you've put into developing this tool and for your prompt responses to my pull requests!

It was perfect for my project, making sure mountain pass and hut labels didn't overlap on the track when generating cycling/hiking posters.
🚴‍♂️ [pretty-gpx](https://github.com/ThomasParistech/pretty-gpx) 🏞️

Really appreciate your work!

**Comment by ckjellson** [comment]
You're welcome!

Cool! I tried with a gpx file of a race I ran recently, but it didn't look great since it was in a city. I guess it would be cool with an option to choose to plot on a map or satellite image instead, but maybe that's out of scope. Anyway, with the tracks in the mountains it looks great 🙂

**Comment by ThomasParistech** [comment]
Yes, unfortunately, it's primarily designed for mountain runs/rides...
However, creating an urban alternative could be fantastic! We would need to define key city landmarks, similar to mountain passes, and find a way to represent the city aesthetically in monochrome. Additionally, the elevation profile could be removed. It would involve quite a few changes, making it an interesting but entirely new project! 😊

**Comment by ckjellson** [comment]
Accidentally ran in the shape of a kangaroo today, so just for fun I imported the gpx file and switched from the elevation map to a simple map, and modified it a bit. Even though the resolution is not great I think it looks quite cool! 😎

![kangaroo_city_run_poster](https://github.com/user-attachments/assets/d1d3a14e-3090-4e53-a9b4-8365106fb2db)

**Comment by ThomasParistech** [comment]
Looks cool!
Where did you get this map from ?

**Comment by ckjellson** [comment]
Smopy with tileserver "https://a.basemaps.cartocdn.com/rastertiles/dark_all/{z}/{x}/{y}.png"

**Comment by JulesL2** [comment]
@ckjellson Now the city maps are supported in pretty_gpx see the documentation for examples ;)
