### ISSUE TITLE
Improve behaviour with seaborn plots

### ISSUE THREAD

**Issue by guidocioni** [ckjellson/textalloc#29]
Hey, 
I'm trying to annotate some of the points on a scatter plot created with `seaborn` which contains multiple scatters organized with a `FacetGrid`.  For some reason the adjustment of labels doesn't always behave as expected, as there are some overlays.

![3a119724-1f0a-439c-a5af-9f2787fad776](https://github.com/user-attachments/assets/2a25abe8-596b-4c2d-94f4-4f9f8ac649e2)

I'm sure it has to do with the method I'm using because I'm trying to use the `map_dataframe` helper function to annotate.
Maybe you have some suggestions? 

```python
g = sns.FacetGrid(
    results, col="city", col_wrap=4, height=2, aspect=1, sharey=False, sharex=False
)
# Create the scatter plot for each facet
g.map_dataframe(
    sns.scatterplot,
    x="temperature_2m_mean_anom",
    y="precipitation_sum_anom",
    hue="year",
)

def annotations(data, **kwargs):
    data = data.copy()
    text_list = []
    x_text = []
    y_text = []
    for _, row in data[data.year.isin([2003, 2018, 2023])].iterrows():
        text_list.append(str(row["year"]))
        x_text.append(row["temperature_2m_mean_anom"])
        y_text.append(row["precipitation_sum_anom"])
    ta.allocate(plt.gca(),
                x_text,
                y_text,
                text_list,
                x_scatter=data["temperature_2m_mean_anom"],
                y_scatter=data["precipitation_sum_anom"],
                min_distance=0.1,
                max_distance=0.8)
g.map_dataframe(annotations) # Iterate through the different group/facet plots
```

**Comment by guidocioni** [comment]
Ok I changed the approach to explicitly provide a scatter object and this seems to work much better

```python
for i, ax in enumerate(g.axes.flat):
    # Get the name of the city corresponding to this axis
    city_name = g.col_names[i]
    # Get the data subset used for this plot (for that specific 'city')
    data = results[results['city'] == city_name]
    # Find the scatter plot object (the first scatter plot collection)
    scatter_obj = ax.collections[0]  # Scatter plots are stored in ax.collections
    text_list = []
    x_text = []
    y_text = []
    for _, row in data[data.year.isin([2003, 2018, 2023])].iterrows():
        text_list.append(str(row["year"]))
        x_text.append(row["temperature_2m_mean_anom"])
        y_text.append(row["precipitation_sum_anom"])
    ta.allocate(ax=ax,
                x=x_text,
                y=y_text,
                text_list=text_list,
                scatter_plot=scatter_obj,
                min_distance=0.1,
                max_distance=0.8,
                linecolor='gray',
                avoid_label_lines_overlap=True,
                textsize=6)
```

Is it possible to avoid text label placements over spine, ticks or tick labels? :)

![fb99f85f-3155-4d52-a049-f48c6f9c5f29](https://github.com/user-attachments/assets/fce71bd2-d4d1-492a-a797-58596a23060a)

**Comment by ckjellson** [comment]
Nice! Another way would be to increase the margin parameter and/or the min_distance parameter, or providing the scatter_sizes of each dot, but passing the scatter object is probably easiest.

There is currently no way to do it automatically. A workaround you could try is to add the tick label positions and the lines of the spines (which I think you can extract from the ax object) as input to the textalloc call as well.

**Comment by guidocioni** [comment]
> Nice! Another way would be to increase the margin parameter, or providing the scatter_sizes of each dot, but passing the scatter object is probably easiest.
> 
> There is currently no way to do it automatically. A workaround you could try is to add the tick label positions and the lines of the spines (which I think you can extract from the ax object) as input to the textalloc call as well.

Ok, I'll look into how to extract those objects from the scatter element. For the moment I'm happy about the result :)
