### ISSUE TITLE
Possibility to add some options

### ISSUE THREAD

**Issue by luisfgranada** [ckjellson/textalloc#3]
Hi Christoffer,

First of all, thanks for such an amazing tool, it works really great. I was wondering if it was possible to add the possibility to format the text, for example add a box around the text, set the zorder, etc.

Thanks!

**Comment by ckjellson** [comment]
Hi, good to hear! Had a pending update, so also simply added the plt.text **kwargs to the function call, so these things should now work.

**Comment by luisfgranada** [comment]
Hi Christoffer,

Thanks for replying so quickly. I have attached two images. The only difference between them is that one of them has 

`bbox=dict(boxstyle="round,pad=0.2", fill=True, alpha=1.0, fc='w', ec="k", lw=0.5)` added to ta.allocate_text function.

You can see that text "RSW3_03" overlaps with a point only when the fancy box is included. Do you think the box is not being considered when making the calculations?

![1](https://github.com/ckjellson/textalloc/assets/65708683/d8e1e06d-14fe-42c8-9521-ad6d5e6f1ef4)
![2](https://github.com/ckjellson/textalloc/assets/65708683/68513c6d-e6df-4eea-8c96-d4dbfffb260d)

For image 1, this is the code:
```
margin = 0.009
min_dist = 0.009
max_dist = 0.012

# Allocate elements labels so they don't overlap
ta.allocate_text(fig, ax, x, y, _id, x_scatter=x,
                        y_scatter=y, textsize=llabel_size,
                        margin=margin, nbr_candidates=100,
                        min_distance=min_dist, max_distance=max_dist,
                        draw_lines=False, draw_all=False
                        )
```

For image 2:
```
margin = 0.009
min_dist = 0.009
max_dist = 0.012

# Allocate elements labels so they don't overlap
ta.allocate_text(fig, ax, x, y, _id, x_scatter=x,
                        y_scatter=y, textsize=llabel_size,
                        margin=margin, nbr_candidates=100,
                        min_distance=min_dist, max_distance=max_dist,
                        draw_lines=False, draw_all=False,
                        bbox=dict(boxstyle="round,pad=0.2", fill=True, alpha=1.0, fc='w', ec="k", lw=0.5)
                        )
```

Thanks.

**Comment by ckjellson** [comment]
No, the box is not considered, but an easy fix would be to increase the margin parameter.
