### ISSUE TITLE
Feature request: different color for each annotation

### ISSUE THREAD

**Issue by gandreadis** [ckjellson/textalloc#4]
Hi, thanks for the great package! It's been really useful. 

I was wondering if it would be possible to add the specification of different colors for individual annotations. Right now, only one `textcolor` can be specified, it would be great if that could also be an array of colors, one per annotation, similar to the `scatter_sizes` option.

**Comment by ckjellson** [comment]
Added possibility for individual colors and sizes!

**Comment by gandreadis** [comment]
Wow, that's great! Thanks for the quick response and implementation :)
