### ISSUE TITLE
Limit location options for label

### ISSUE THREAD

**Issue by jordanplanders** [ckjellson/textalloc#9]
Hi again! In my quest of labelling my timeline one edge of which is on the x-axis, two adjustments would help a great deal:
1. the ability to set an offset between the point being annotated and the label
2. the ability to limit the option space for the label location (e.g. only below the point)

Hoping these are interesting to you too!

**Comment by jordanplanders** [comment]
It did help! 

One thing that is emerging however, is that it seems logical that "due north" (or south, etc.) would be the first pick option for "north" with other options to follow (I think it is set up so that you amass candidates and then pick the first one in the viable list), and the center of the text box would be connected to the point (I think this doesn't quite take care of itself because the text boxes are understood as bottom-left and top-right, so "closest point" becomes one of the two). 

In my timeline use case, I have a small conundrum in that parts of the timeline are more crowded than other parts. It is giving me pause to think about logical ways to handle spacious areas and not so spacious ones. It would be neatest to use the min_distance=max_distance trick to get them neatly in a row, but that gets trick where it's more densely populated.

Here's a minimum example of my timeline situation. 

THANK YOU!!!!!!!

```
colors = color=['r', 'm', 'orange', 'blue', 'green', 'aqua', 'navy', 'pink']#['r', 'b']#'r' if ik%2 ==0 else 'b' for ik, _ts in enumerate(geo_ts)]
ceno_intervals_pairs = [[0.0, 0.01],[0.01, 1.6], [1.6, 5.3],[5.3, 23.7],[23.7, 36.6],[36.6, 57.8],[57.8, 66.4]]
x_locs = np.array([5.000e-03, 8.050e-01, 3.450e+00, 1.450e+01, 3.015e+01, 4.720e+01, 6.210e+01])
labels = np.array(['Holocene', 'Pleistocene', 'Pliocene', 'Miocene', 'Oligocene', 'Eocene', 'Paleocene'], dtype=object)
y_locs = np.array([-.1 for x_loc in x_locs])
fig, ax = plt.subplots(2, 1, figsize=(10,1))
for ik, _ts in enumerate(ceno_intervals_pairs):
    c = color[ik]
    a = .2

    ax[1].axvspan(_ts[0], _ts[1], facecolor=c, alpha=a)

for ip in [0,1]:
    ax[ip].grid(False)
    for side in ['left', 'right', 'bottom']:
        ax[ip].spines[side].set_visible(False)
    
    ax[ip].set_yticks([])
    ax[ip].tick_params(axis='x', which='both', length=0)
    ax[ip].set_xlabel('')
    ax[ip].set_ylabel('')
    ax[ip].set_yticklabels([])
xlim = ax[1].get_xlim()
ax[0].set_xlim(xlim)
ax[0].set_xticklabels([])

min_distance=.875#85
margin=0
ta.allocate_text(fig,ax[0],
                 x_locs,y_locs,
                labels,
                min_distance=min_distance,#[xmin_distance,ymin_distance], #0.04,
                max_distance=min_distance,#+.15,#[xmin_distance+40,ymin_distance +10],#0.842,
                margin=margin,
                linewidth=0.5,
                draw_all=True,
                seed=3,
                mode='north',
                 **dict( va='bottom', ha='center')
```

<img width="844" alt="mve_timeline" src="https://github.com/ckjellson/textalloc/assets/10099739/bb673b4f-2712-4124-abfc-b66fb6c82c86">

**Comment by ckjellson** [comment]
I agree. Was not able to run your code, but added candidates if direction (before mode) is provided of the set direction.
With the following code:

```
x = [1,2,3,4,5,10,15,16,20]
y1 = [0 for _ in x]
y2 = [1 for _ in x]
labels = [f"long_word_{i}" for i in range(len(x))]
fig,ax = plt.subplots(figsize=(10,2))
ax.scatter(x,y1)
ax.scatter(x,y2,s=0)
ta.allocate_text(fig,ax,x,y1,labels,direction="north", seed=42, linewidth=0.5)
```
you would now get this:
![image](https://github.com/ckjellson/textalloc/assets/37980849/36c0fca9-bef1-4b1f-b78e-c16645a023e4)

Hope that helps again!
